import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, useLocation } from 'react-router-dom';
import { motion, AnimatePresence, MotionConfig, useReducedMotion } from 'motion/react';
import { ArrowUpRight, ArrowRight, Menu, X, MapPin, ChevronDown, ChevronLeft, ChevronRight, Plus, HeartHandshake, Smile, CircleDot, ShieldCheck, MessageCircle } from 'lucide-react';
import './style.css';

const phone = '5562981195003';
const whatsapp = (subject = '') => `https://wa.me/${phone}?text=${encodeURIComponent(`Olá! Vim pelo site da Turíbio e gostaria de ${subject ? `informações sobre ${subject}` : 'agendar uma avaliação'}.`)}`;

const teamImages = [
  '731158349_17942677818247738_4921347707780340768_n.jpg',
  '742771039_17946492786247738_7511137986732517166_n.webp',
  '746164079_17945692668247738_4256013866608381426_n.webp',
  '746285169_17945692620247738_1989676438566413693_n.webp',
  '748053991_17945692635247738_7823210411068339356_n.webp',
  '749681241_17945692563247738_1020044448583227065_n.webp',
  '753231592_17946492798247738_7659393754494299367_n.webp',
];

function LoadingOverlay(){const [visible,setVisible]=useState(true);useEffect(()=>{const t=setTimeout(()=>setVisible(false),1350);return()=>clearTimeout(t)},[]);return <AnimatePresence>{visible&&<motion.div className="loading-overlay" initial={{opacity:1}} exit={{opacity:0}} transition={{duration:.5}}><motion.div className="loading-mark" initial={{scale:.9,opacity:0}} animate={{scale:1,opacity:1}}><Tooth/><span>TURÍBIO</span></motion.div><div className="loading-line"><motion.i initial={{scaleX:0}} animate={{scaleX:1}} transition={{duration:1,ease:[.65,0,.35,1]}}/></div></motion.div>}</AnimatePresence>}

function Typewriter(){const phrases=['Nosso cuidado.','Sua confiança.','Seu novo sorriso.','Uma boa conversa.'];const [index,setIndex]=useState(0);const [text,setText]=useState('');const [deleting,setDeleting]=useState(false);useEffect(()=>{const full=phrases[index];const done=!deleting&&text===full;const empty=deleting&&text==='';const delay=done?1500:empty?260:deleting?42:72;const t=setTimeout(()=>{if(done)return setDeleting(true);if(empty){setDeleting(false);setIndex(v=>(v+1)%phrases.length);return}setText(deleting?full.slice(0,text.length-1):full.slice(0,text.length+1))},delay);return()=>clearTimeout(t)},[text,deleting,index]);return <em className="typewriter">{text}<span aria-hidden="true">|</span></em>}

function TeamCoverflow(){
  const [active,setActive]=useState(0);
  const [compact,setCompact]=useState(false);
  const wheelLock=useRef(false);
  useEffect(()=>{
    const mq=window.matchMedia('(max-width: 760px)');
    const sync=()=>setCompact(mq.matches);
    sync(); mq.addEventListener?.('change',sync);
    return()=>mq.removeEventListener?.('change',sync);
  },[]);
  const go=(next)=>setActive(Math.max(0,Math.min(teamImages.length-1,next)));
  const onWheel=(e)=>{
    if(Math.abs(e.deltaY)<Math.abs(e.deltaX) || wheelLock.current)return;
    e.preventDefault();
    wheelLock.current=true;
    go(active+(e.deltaY>0?1:-1));
    window.setTimeout(()=>{wheelLock.current=false},420);
  };
  const spacing=compact?154:238;
  return <section className="team-coverflow-section" aria-labelledby="team-title">
    <div className="container team-coverflow-head">
      <Reveal><span className="eyebrow">NOSSA EQUIPE</span><h2 id="team-title">Presença, técnica<br/><em>e cuidado humano.</em></h2></Reveal>
      <div className="team-coverflow-meta"><p>Deslize para conhecer a equipe.</p><div className="coverflow-controls"><button onClick={()=>go(active-1)} disabled={active===0} aria-label="Profissional anterior"><ChevronLeft/></button><span>{String(active+1).padStart(2,'0')} / {String(teamImages.length).padStart(2,'0')}</span><button onClick={()=>go(active+1)} disabled={active===teamImages.length-1} aria-label="Próximo profissional"><ChevronRight/></button></div></div>
    </div>
    <div className="coverflow-viewport" onWheel={onWheel}>
      <motion.div className="coverflow-drag" drag="x" dragConstraints={{left:0,right:0}} dragElastic={.12} onDragEnd={(_,info)=>{if(info.offset.x<-55||info.velocity.x<-350)go(active+1);else if(info.offset.x>55||info.velocity.x>350)go(active-1)}}>
        {teamImages.map((src,i)=>{const d=i-active;const abs=Math.abs(d);return <motion.button key={src} type="button" className={`coverflow-card ${d===0?'is-active':''}`} onClick={()=>go(i)} aria-label={`Ver foto ${i+1} da equipe`} animate={{x:d*spacing,scale:d===0?1:abs===1?.86:.72,rotateY:d===0?0:d<0?38:-38,opacity:abs>2?0:abs===2?.32:abs===1?.72:1,z:d===0?60:0}} transition={{type:'spring',stiffness:240,damping:28,mass:.75}} style={{zIndex:20-abs}}>
          <img src={`/images/equipe/${src}`} alt={`Equipe Turíbio — registro ${i+1}`} loading={i===0?'eager':'lazy'}/><span className="coverflow-glow"/>
        </motion.button>})}
      </motion.div>
    </div>
    <div className="coverflow-dots" aria-label="Selecionar foto da equipe">{teamImages.map((_,i)=><button key={i} onClick={()=>go(i)} className={i===active?'active':''} aria-label={`Ir para foto ${i+1}`}/>)}</div>
  </section>
}

const services = [
  { slug:'implantes', n:'01', title:'Implantes dentários', summary:'Um novo caminho para recuperar seu sorriso.', icon:CircleDot, intro:'A ausência de um dente merece um olhar individual.', text:'A avaliação de implantes começa com uma conversa sobre suas necessidades e uma análise da saúde bucal. É a partir desse cuidado que a equipe pode discutir as possibilidades para o seu caso.', steps:['Conversa sobre suas necessidades e histórico.','Avaliação clínica e exames, quando indicados.','Apresentação das possibilidades e do plano de tratamento.'], questions:[['Como saber se um implante é indicado para mim?','A indicação depende de avaliação individual. Entre em contato para conversar com a equipe e solicitar uma consulta.'],['Posso saber o valor antes da avaliação?','O orçamento depende do planejamento e das necessidades identificadas. A equipe pode explicar como funciona a avaliação pelo WhatsApp.']] },
  { slug:'proteses', n:'02', title:'Próteses e reabilitação', summary:'Cuidado para voltar a sorrir com confiança.', icon:Smile, intro:'Cada sorriso tem uma história. O cuidado também.', text:'Na consulta, a equipe avalia suas necessidades e conversa sobre as possibilidades de reabilitação oral. O objetivo é construir um planejamento adequado à sua situação, com explicações claras sobre cada etapa.', steps:['Escuta das suas dificuldades e expectativas.','Avaliação da condição bucal.','Conversa sobre opções, cuidados e acompanhamento.'], questions:[['Como escolher o tipo de prótese?','Essa escolha deve ser feita com o profissional após avaliar seu caso e discutir as alternativas.'],['Já uso uma prótese. Posso agendar?','Sim. Conte à recepção o motivo da sua visita para solicitar uma avaliação.']] },
  { slug:'estetica', n:'03', title:'Estética dental', summary:'Naturalidade para um sorriso que é seu.', icon:Smile, intro:'O primeiro passo é entender o que você deseja mudar.', text:'Um planejamento estético começa com a saúde bucal e com a escuta das suas expectativas. Converse com a equipe sobre clareamento e outras possibilidades para o seu sorriso, sempre com avaliação individual.', steps:['Conversa sobre o que incomoda e suas expectativas.','Avaliação da saúde bucal.','Planejamento e esclarecimento das alternativas.'], questions:[['Vocês realizam clareamento?','O clareamento aparece entre os cuidados divulgados pela clínica. Fale com a equipe para conhecer o atendimento e solicitar uma avaliação.'],['Como saber qual procedimento escolher?','Você não precisa chegar com essa decisão tomada. A consulta é o momento de conhecer as opções adequadas ao seu caso.']] },
  { slug:'ortodontia', n:'04', title:'Aparelhos e alinhadores', summary:'Planejamento para cuidar do alinhamento do sorriso.', icon:ShieldCheck, intro:'Um tratamento que começa com planejamento.', text:'Conheça o atendimento em ortodontia da Turíbio. Na avaliação, você pode conversar sobre aparelhos e alinhadores, esclarecer dúvidas e entender como funciona o acompanhamento.', steps:['Avaliação inicial e conversa sobre seus objetivos.','Exames e planejamento, conforme indicação.','Orientação sobre o tratamento e as consultas de acompanhamento.'], questions:[['Aparelho ou alinhador: qual escolher?','A escolha depende da avaliação e do planejamento profissional. A equipe explica as opções disponíveis para o seu caso.'],['Qual é o tempo de tratamento?','O prazo é individual e deve ser discutido após a avaliação.']] },
  { slug:'clinica-geral', n:'05', title:'Cuidado e prevenção', summary:'Atenção ao seu sorriso em todas as fases.', icon:HeartHandshake, intro:'O cuidado cotidiano também merece atenção.', text:'A Turíbio oferece atendimento clínico geral para acompanhar sua saúde bucal. Agende uma avaliação para conversar sobre prevenção, limpeza e outras necessidades do seu sorriso.', steps:['Escuta do motivo da consulta.','Avaliação clínica.','Orientações e definição dos próximos cuidados.'], questions:[['Posso marcar uma consulta de rotina?','Sim. Entre em contato pelo WhatsApp para consultar os horários disponíveis.'],['Preciso escolher um tratamento antes de agendar?','Não. Você pode solicitar uma avaliação e contar à equipe o que está procurando.']] },
];

function Tooth({className=''}) {return <svg className={className} width="38" height="46" viewBox="0 0 44 50" fill="none" aria-hidden="true"><path d="M22 7C15 2 5 2 4 12c-1 8 5 13 6 20s2 13 5 13c4 0 3-18 8-18s4 18 8 18c3 0 4-9 5-15s6-12 4-19C37 0 27 5 22 7Z" stroke="currentColor" strokeWidth="1.4"/><path d="M9 15c7-3 12 7 24-4M16 7c4 4 7 5 12 5" stroke="currentColor" strokeWidth="1.2"/></svg>}
function Brand(){return <Link className="brand" to="/" aria-label="Turíbio Odontologia, início"><Tooth/><span>TURÍBIO<small>ODONTOLOGIA</small></span></Link>}
function WhatsApp({children='Agendar uma avaliação', subject='', className=''}) {return <motion.a whileHover={{y:-2}} whileTap={{scale:.98}} className={`button ${className}`} href={whatsapp(subject)} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={18}/></motion.a>}
function Reveal({children,className='',delay=0}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.65,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
// Original screenshots are kept intact; only the displayed viewport is cropped.
function Photo({source='clinica',col=4,row=1,alt,className=''}){const zoom=source==='clinica'?1.32:1.18;return <div className={`photo ${className}`}><img src={`/images/${source}.png`} alt={alt} loading={col===4?'eager':'lazy'} style={{width:`${500*zoom}%`,height:`${200*zoom}%`,left:`-${col*100*zoom+(zoom-1)*50}%`,top:`-${row*100*zoom+(zoom-1)*50}%`}}/></div>}
function Header(){const [open,setOpen]=useState(false);const location=useLocation();useEffect(()=>setOpen(false),[location]);useEffect(()=>{if(!open)return;const close=e=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open]);const links=[['Tratamentos','/#tratamentos'],['Nossa essência','/#clinica'],['Como funciona','/#jornada'],['Localização','/#contato']];return <header className="header"><div className="container nav"><Brand/><nav className="desktop-nav" aria-label="Navegação principal">{links.map(([t,h])=><Link key={h} to={h}>{t}</Link>)}</nav><WhatsApp className="header-cta">Vamos conversar</WhatsApp><button className="menu-toggle" aria-label={open?'Fechar menu':'Abrir menu'} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div><AnimatePresence>{open&&<motion.nav id="mobile-menu" aria-label="Navegação mobile" className="mobile-nav" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{links.map(([t,h])=><Link onClick={()=>setOpen(false)} key={h} to={h}>{t}<ArrowUpRight size={18}/></Link>)}<WhatsApp/></motion.nav>}</AnimatePresence></header>}
function Accordion({items}){const [active,setActive]=useState(null);const reduced=useReducedMotion();return <div className="accordion">{items.map(([q,a],i)=><div className="faq-item" key={q}><h3><button aria-expanded={active===i} aria-controls={`answer-${i}`} onClick={()=>setActive(active===i?null:i)}>{q}<motion.span animate={{rotate:active===i?45:0}}><Plus size={20}/></motion.span></button></h3><motion.div id={`answer-${i}`} role="region" aria-label={q} initial={false} animate={{height:active===i?'auto':0,opacity:active===i?1:0}} transition={{duration:reduced?0:.25}} style={{overflow:'hidden'}} inert={active!==i?true:undefined}><p>{a}</p></motion.div></div>)}</div>}
function Home(){return <>
  <section className="hero container">
    <div className="hero-copy"><Reveal><span className="eyebrow"><span className="little-line"/> ODONTOLOGIA FEITA DE CUIDADO</span><h1>Seu sorriso.<br/>Sua história.<br/><Typewriter/></h1><p>Um espaço para ouvir você, acolher suas dúvidas e cuidar do seu sorriso em cada etapa.</p><WhatsApp/><a className="hero-location" href="https://maps.app.goo.gl/z1x1SN4i8SE5iHdq6" target="_blank" rel="noopener noreferrer"><MapPin size={15}/> Setor Garavelo · Aparecida de Goiânia</a></Reveal></div>
    <Reveal className="hero-visual" delay={.12}><div className="hero-photo-frame"><img className="hero-direct-image" src="/images/hero-consultorio.png" alt="Consultório da Turíbio Odontologia"/><div className="photo-shade"/><span className="image-caption">BEM-VINDO À TURÍBIO</span></div><div className="round-seal"><Tooth/><span>CUIDAR É<br/>O NOSSO JEITO.</span></div><div className="hero-note"><span className="note-icon"><HeartHandshake size={26}/></span><div><strong>Antes do tratamento,<br/>uma boa conversa.</strong><span>Estamos aqui para ouvir você.</span></div></div></Reveal>
    <a href="#tratamentos" className="scroll-cue">CONHEÇA NOSSO CUIDADO <ChevronDown size={15}/></a>
  </section>
  <div className="values-strip"><div className="container"><span><Plus size={14}/> Atenção em cada detalhe</span><span><Plus size={14}/> Planejamento individual</span><span><Plus size={14}/> Cuidado com proximidade</span></div></div>
  <section className="section container treatments" id="tratamentos"><Reveal className="section-heading"><div><span className="eyebrow">01 / CUIDADOS PARA VOCÊ</span><h2>Cada sorriso pede<br/><em>um cuidado diferente.</em></h2></div><p>Da prevenção à reabilitação, conheça as possibilidades e converse com a nossa equipe.</p></Reveal><div className="treatment-grid">{services.map((s,i)=><Reveal delay={i*.05} key={s.slug}><Link className="treatment-card" to={`/tratamentos/${s.slug}`}><div className="card-top"><s.icon size={31} strokeWidth={1.2}/><span>{s.n}</span></div><h3>{s.title}</h3><p>{s.summary}</p><span className="card-link">Conhecer tratamento <ArrowUpRight size={19}/></span></Link></Reveal>)}<Reveal delay={.2}><div className="treatment-card help-card"><MessageCircle size={30} strokeWidth={1.2}/><h3>Por onde<br/>começar?</h3><p>Você não precisa decidir sozinho. Vamos conversar.</p><a href={whatsapp()} target="_blank" rel="noopener noreferrer" className="card-link">Falar com a equipe <ArrowUpRight size={19}/></a></div></Reveal></div></section>
  <section className="clinic-section" id="clinica"><div className="container clinic-grid"><Reveal className="clinic-images clinic-images-single"><div className="photo portrait essence-photo"><img className="essence-direct-image" src="/images/essencia-protese.png" alt="Resultado de prótese parcial removível realizado pela Turíbio"/></div><span className="photo-label">GENTE QUE CUIDA DE GENTE.</span></Reveal><Reveal className="clinic-copy"><span className="eyebrow">02 / NOSSA ESSÊNCIA</span><h2>Mais que cuidar<br/>de dentes.<br/><em>Cuidar de pessoas.</em></h2><p>Acreditamos que o cuidado começa quando você se sente à vontade. Para perguntar, contar sua história e falar sobre o que espera do seu sorriso.</p><p>Na Turíbio, queremos que você conheça o espaço, converse com a equipe e entenda os próximos passos do seu atendimento.</p><div className="clinic-detail"><HeartHandshake size={22}/><span>Uma conversa aberta.<br/><strong>Um cuidado pensado para você.</strong></span></div><WhatsApp className="button-outline">Conhecer a clínica</WhatsApp></Reveal></div></section>
  <TeamCoverflow/>
  <section className="section container info-section"><Reveal><span className="eyebrow">SOBRE NÓS</span><h2>Sobre a Turíbio</h2><p className="info-lead">Aqui na nossa clínica dentária, estamos comprometidos em oferecer tratamentos odontológicos de alta qualidade para toda a família. Do cuidado preventivo aos procedimentos mais complexos, nossa equipe está pronta para cuidar de você e da sua saúde bucal.</p></Reveal><Reveal><span className="eyebrow">HORÁRIO DE ATENDIMENTO</span><h2>Quando receber você.</h2><div className="hours-card"><span>Segunda-feira <b>08:00 às 18:00</b></span><span>Terça-feira <b>08:00 às 18:00</b></span><span>Quarta-feira <b>08:00 às 18:00</b></span><span>Quinta-feira <b>08:00 às 18:00</b></span><span>Sexta-feira <b>08:00 às 18:00</b></span><span>Sábado <b>08:00 às 12:30</b></span></div></Reveal></section>
  <section className="services-list-section"><div className="container"><Reveal className="center-heading"><span className="eyebrow">NOSSOS SERVIÇOS</span><h2>Cuidando de toda sua saúde bucal.</h2></Reveal><div className="services-list">{[['Extração dentária','Resolva problemas dentários de forma segura'],['Limpeza dental','Mantenha sua saúde bucal em dia'],['Implante dentário','Recupere seu sorriso por completo, volte a sorrir.'],['Odontologia estética','Transforme seu sorriso com lentes e facetas'],['Tratamento de canal','Salve seu dente e evite extrações'],['Atendimento infantil','Cuide da saúde bucal dos pequenos desde cedo']].map(([t,d])=><Reveal key={t}><div className="service-mini"><CircleDot/><div><h3>{t}</h3><p>{d}</p></div></div></Reveal>)}</div></div></section>
  <section className="section container journey" id="jornada"><Reveal className="center-heading"><span className="eyebrow">03 / SEU PRIMEIRO PASSO</span><h2>Começa com uma conversa.<br/><em>Continua com cuidado.</em></h2></Reveal><div className="steps">{[['01','Vamos conversar','Envie uma mensagem pelo WhatsApp. Nossa equipe ajuda você a consultar a disponibilidade e solicitar uma avaliação.'],['02','Queremos ouvir você','Na consulta, conte suas necessidades e expectativas. É o momento de conhecer a equipe e esclarecer suas dúvidas.'],['03','Um plano para seu sorriso','Após a avaliação, converse sobre as possibilidades de tratamento, as etapas e os próximos cuidados.']].map(([n,t,p],i)=><Reveal key={n} delay={i*.1}><span className="step-number">{n}</span><h3>{t}</h3><p>{p}</p></Reveal>)}</div><Reveal className="journey-action"><WhatsApp>Dar o primeiro passo</WhatsApp><span>Agendamento sujeito à confirmação da equipe.</span></Reveal></section>
  <section className="space-section"><div className="container space-grid"><Reveal><span className="eyebrow">UM ESPAÇO PARA ACOLHER</span><h2>Pode chegar.<br/><em>Sinta-se à vontade.</em></h2><p>Conheça um pouco do ambiente onde vamos receber você. A próxima conversa pode ser aqui.</p><a className="text-link" href="https://maps.app.goo.gl/z1x1SN4i8SE5iHdq6" target="_blank" rel="noopener noreferrer">Veja como nos encontrar <ArrowUpRight size={19}/></a></Reveal><Reveal className="space-photo"><img className="direct-space-image" src="/images/recepcao-nova.png" alt="Recepção da Turíbio Odontologia"/></Reveal><Reveal className="space-photo narrow"><img className="direct-space-image" src="/images/consultorio-novo.jpg" alt="Consultório da Turíbio Odontologia"/></Reveal></div></section>
  <section className="section container faq-section"><Reveal><span className="eyebrow">04 / PODE PERGUNTAR</span><h2>Suas dúvidas<br/><em>têm espaço aqui.</em></h2><p>Não encontrou o que precisava?<br/>Converse diretamente com a equipe.</p><a className="text-link" href={whatsapp()} target="_blank" rel="noopener noreferrer">Tirar uma dúvida <ArrowUpRight size={18}/></a></Reveal><Reveal><Accordion items={[
    ['Como agendar uma avaliação?','Use um dos botões de contato do site — como “Vamos conversar”, “Dar o primeiro passo” ou “Conversar pelo WhatsApp”. Você será direcionado ao WhatsApp da recepção para consultar a disponibilidade e solicitar sua avaliação. O horário é confirmado pela equipe.'],
    ['Onde fica a Turíbio?','A clínica fica no Setor Garavelo, em Aparecida de Goiânia (GO). Use o link de localização do site para abrir a rota diretamente no Google Maps.'],
    ['Preciso saber qual tratamento quero?','Não. Você pode começar contando o que está procurando ou o que incomoda no seu sorriso. Na avaliação, o profissional orienta os próximos passos.'],
    ['Como consultar valores e formas de pagamento?','Fale com a recepção sobre as condições de atendimento. O orçamento de um tratamento depende da avaliação e do planejamento do seu caso.'],
    ['Quais são os horários de atendimento?','Atendemos de segunda a sexta-feira, das 08:00 às 18:00, e aos sábados, das 08:00 às 12:30. Para agendar, consulte a disponibilidade do horário desejado com a recepção pelo WhatsApp.']
  ]}/></Reveal></section>
  <section id="contato" className="contact-section"><div className="container contact-grid"><Reveal><span className="eyebrow">SEU SORRISO MERECE ATENÇÃO</span><h2>Vamos cuidar<br/><em>do seu próximo sorriso?</em></h2><p>Fale com a nossa equipe e solicite sua avaliação.</p><WhatsApp className="button-gold">Conversar pelo WhatsApp</WhatsApp></Reveal><Reveal className="contact-card"><MapPin size={25} strokeWidth={1.3}/><span className="eyebrow">ENCONTRE A TURÍBIO</span><h3>Perto de você.<br/>No Setor Garavelo.</h3><p>Aparecida de Goiânia · GO</p><a href="https://maps.app.goo.gl/z1x1SN4i8SE5iHdq6" target="_blank" rel="noopener noreferrer">Abrir localização <ArrowUpRight size={18}/></a><div className="contact-phone"><MessageCircle size={18}/><a href={whatsapp()} target="_blank" rel="noopener noreferrer">(62) 98119-5003</a></div></Reveal></div></section>
</>}
function Treatment(){const {pathname}=useLocation();const item=services.find(s=>pathname.endsWith('/'+s.slug));if(!item)return <NotFound/>;return <main><section className="container detail-hero"><Link className="text-link" to="/#tratamentos">← Todos os tratamentos</Link><Reveal><span className="eyebrow">TURÍBIO ODONTOLOGIA / {item.title.toUpperCase()}</span><h1>{item.title}</h1><h2><em>{item.intro}</em></h2><p>{item.text}</p><WhatsApp subject={item.title.toLowerCase()}>Conversar sobre {item.slug==='implantes'?'implantes':'o tratamento'}</WhatsApp></Reveal></section><section className="detail-band"><div className="container"><span className="eyebrow">COMO COMEÇAMOS</span><div className="steps">{item.steps.map((s,i)=><Reveal key={s}><span className="step-number">0{i+1}</span><h3>{s}</h3></Reveal>)}</div></div></section><section className="section container faq-section"><div><span className="eyebrow">ANTES DA SUA VISITA</span><h2>Vamos esclarecer<br/><em>suas dúvidas.</em></h2></div><Accordion items={item.questions}/></section><section className="detail-end container"><h2>O próximo passo é <em>uma conversa.</em></h2><WhatsApp subject={item.title.toLowerCase()}/></section></main>}
function Privacy(){return <main className="container privacy"><span className="eyebrow">TURÍBIO ODONTOLOGIA</span><h1>Privacidade</h1><p>Este site apresenta informações sobre a clínica e oferece links para contato. Não há formulário de cadastro, área de login ou envio de dados clínicos neste site.</p><h2>Contato pelo WhatsApp</h2><p>Ao clicar em um botão de contato, você será direcionado ao WhatsApp. A mensagem sugerida só será enviada se você decidir enviá-la. O uso desse serviço está sujeito às políticas do próprio WhatsApp.</p><h2>Conteúdo e navegação</h2><p>As fontes e imagens são carregadas junto com o site. Esta versão não utiliza ferramentas de publicidade ou análise de navegação. O provedor de hospedagem poderá processar registros técnicos necessários à disponibilização do site.</p><h2>Dúvidas</h2><p>Para esclarecer questões sobre o atendimento e o uso das informações que você compartilha com a clínica, entre em contato com a equipe pelo WhatsApp.</p><WhatsApp>Falar com a equipe</WhatsApp></main>}
function NotFound(){return <main className="container privacy"><h1>Página não encontrada.</h1><Link className="button" to="/">Voltar ao início <ArrowRight size={18}/></Link></main>}
function Footer(){return <footer><div className="container footer-top"><Brand/><p>Cuidar do seu sorriso.<br/>Com atenção, em cada detalhe.</p><a href="https://www.instagram.com/turibio_odontologia/" target="_blank" rel="noopener noreferrer">Nosso Instagram <ArrowUpRight size={17}/></a></div><div className="container footer-bottom"><span>© 2026 Um produto <a href="https://codental.com.br/" target="_blank" rel="noopener noreferrer"><strong>Codental</strong></a>. Todos os direitos reservados.</span><span>Setor Garavelo · Aparecida de Goiânia</span><Link to="/privacidade">Privacidade</Link></div></footer>}
function ScrollManager(){const {pathname,hash}=useLocation();useEffect(()=>{const title=services.find(s=>pathname==='/tratamentos/'+s.slug)?.title;document.title=title?`${title} | Turíbio Odontologia`:pathname==='/privacidade'?'Privacidade | Turíbio Odontologia':'Turíbio Odontologia · Cuidado que faz sorrir';if(hash){requestAnimationFrame(()=>document.getElementById(hash.slice(1))?.scrollIntoView({behavior:'instant'}))}else window.scrollTo({top:0,behavior:'instant'});},[pathname,hash]);return null}
function App(){return <MotionConfig reducedMotion="user"><BrowserRouter><LoadingOverlay/><ScrollManager/><a className="skip-link" href="#main">Pular para o conteúdo</a><Header/><div id="main"><Routes><Route path="/" element={<main><Home/></main>}/><Route path="/tratamentos/:slug" element={<Treatment/>}/><Route path="/privacidade" element={<Privacy/>}/><Route path="*" element={<NotFound/>}/></Routes></div><Footer/></BrowserRouter></MotionConfig>}
createRoot(document.getElementById('root')).render(<App/>);
